# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

def shared_pods
  pod 'SwiftyJSON'
  pod 'Alamofire'
end

target 'BitFreeze' do
	shared_pods
end

target 'BitFreeze WatchKit App' do
end

target 'BitFreeze WatchKit Extension' do
	platform :watchos, '2.0'
  	shared_pods
end





