# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'BitFreeze' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire', '~> 3.3'
  # Pods for BitFreeze

end

target 'BitFreeze WatchKit App' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BitFreeze WatchKit App

end

target 'BitFreeze WatchKit Extension' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BitFreeze WatchKit Extension

end
